### ISSUE TITLE
Endlos rebbots?

### ISSUE THREAD

**Issue by Tarnatos** [viisauksena/gluon-fffr#1]
Hey,

wie werden endlos reboots bei isolierten Knoten vermeiden?

Gruß
Tarnatos

**Comment by viisauksena** [comment]
would be easier for people to answer if you add more details, i guess you mean emergency.sh ... 
we dont stop them from rebooting after 10 minutes , this is sufficient to do anything if you are physically next to the node. 
this is not directly for general use, because some people may be happy with not connected nodes in general (mainly using it as switch)
in the cases where this is used by us - no batman connectivity is meaning the node failed in its purpose - and 10 minute reboot cycle do no harm at all.
but we stretched rebooting to 10 minutes and try to self repair if possible with more and more aggressive steps (in terms of network interruption) - where reboot is the ultima ratio

**Comment by viisauksena** [comment]
since no further info was given i close this issue here
